# Generated by Django 4.0.5 on 2024-05-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleopatraApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancer',
            name='id',
        ),
        migrations.AlterField(
            model_name='dancer',
            name='dancerID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
    ]
