# Generated by Django 4.0.5 on 2024-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleopatraApp', '0002_remove_dancer_id_alter_dancer_dancerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancer',
            name='courses',
        ),
        migrations.AddField(
            model_name='dancer',
            name='courses',
            field=models.ManyToManyField(related_name='dancers', to='CleopatraApp.course'),
        ),
    ]
