# Generated by Django 4.0.5 on 2024-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleopatraApp', '0003_remove_dancer_courses_dancer_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='CleopatraApp.course'),
        ),
    ]
