# Generated by Django 4.0.5 on 2024-06-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleopatraApp', '0004_alter_dancer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
